library(tidyverse)
library(here)
library(Seurat)
library(cowplot)
library(biomaRt)
library(org.Mm.eg.db)
library(clusterProfiler)
library(MAST)
library(RColorBrewer)
library(wesanderson)
library(UpSetR)

#####Analysis on new normalization#####
#####Load in and analyze data generated by SCOP(provided by Jonatan Thompson#####
SCOP<- readRDS(here("pilot_data/Output/data/SCOP_2021_0132.210202_liver.umap.rds"))
#save plot with HTO labels
hto_plot <- DimPlot(SCOP)

VlnPlot(object = SCOP, 
        features =c("nCount_RNA", 
                    "nFeature_RNA"), 
        pt.size = 0.1,
        group.by = "hash.ID")
SCOP <- SCTransform(object = SCOP)
npcs <- 35 # max n PCs to check
randomSeed <- 12345
set.seed(randomSeed)
#runPCA
SCOP <- RunPCA(SCOP, 
               npcs=npcs, 
               seed.use=randomSeed, 
               verbose=F)
#runUMAP
SCOP <- RunUMAP(SCOP, 
                dims = 1:npcs, 
                seed.use = randomSeed+1)
SCOP <- FindNeighbors(SCOP,
                      reduction = "pca", 
                      dims = 1:npcs)

SCOP <- FindClusters(SCOP,
                     random.seed = randomSeed, 
                     resolution = 1.2,
                     verbose = FALSE)

annot_clust = "SCT_snn_res.1.2"

vec_color_clust = colorRampPalette(brewer.pal(n=11, name="RdYlBu"))(length(unique(SCOP@meta.data[[annot_clust]])))

names(vec_color_clust) = unique(SCOP@meta.data[[annot_clust]])
DimPlot(SCOP, 
        group.by=annot_clust,
        cols = vec_color_clust,repel = T,pt.size = 0.1, label.size = 5,
        label = TRUE) + NoLegend()
annot_hash = "hash.ID"

vec_color_hash=wesanderson::wes_palette("Royal1")
vec_color_hash = c(vec_color_hash, wesanderson::wes_palette("Zissou1")[c(1,3)])

names(vec_color_hash) = unique(SCOP@meta.data[[annot_hash]])
DimPlot(SCOP, 
        group.by="hash.ID",
        cols = vec_color_hash,
        repel = T,
        pt.size = 0.1, label.size = 5,
        label = TRUE) + NoLegend()

annotations = "hash.ID"

#Analyze with the MAST package

Idents(SCOP) <-SCOP@meta.data[[annotations]]

annots = Idents(SCOP) %>% table %>% names 
# for each cluster label, find markers
list_iterable = list("X"=annots)

fun = function(annot) {tryCatch({
  FindMarkers(SCOP,  
              ident.1 = annot,
              only.pos = T,
              test.use  ="MAST",
              max.cells.per.ident=1000,
              random.seed=randomSeed,
              verbose = T)
}, 
error = function(err) {
  NA_character_
})}

list_markers=NULL
list_markers <- lapply(FUN=fun, "X"=list_iterable[[1]])



# add the gene and cluster as a column
list_markers <- mapply(function(df_markers, annots) {
  if (!all(sapply(df_markers, is.na))) {
    cbind("feature" = rownames(df_markers), "annotation"=rep(annots, nrow(df_markers)), df_markers)
  } else {
    NA_character_
  }
},
df_markers=list_markers, 
annot=names(table(Idents(SCOP))), SIMPLIFY=F)

# check for NAs from errors
list_markers <- list_markers[!sapply(list_markers, function(markers) all(is.na(markers)))]

# reduce list of dataframes to a single dataframe
df_markers_hash <- Reduce(x=list_markers, f=rbind)
rownames(df_markers_hash) <- NULL

df_markers_hash$p_val_adj <- p.adjust(p=df_markers_hash$p_val, method="fdr")


#openxlsx::write.xlsx(x = df_markers_hash, file=here::here("pilot_data/Output/HTO_comparison.xlsx"))

#Analysis of clusters
annotations = "SCT_snn_res.1.2"
Idents(SCOP) <-SCOP@meta.data[[annotations]]

annots = Idents(SCOP) %>% table %>% names 
# for each cluster label, find markers
list_iterable = list("X"=annots)
fun = function(annot) {tryCatch({
  FindMarkers(SCOP,  
              ident.1 = annot,
              only.pos = T,
              test.use  ="MAST",
              max.cells.per.ident=1000,
              random.seed=randomSeed,
              verbose = T)
}, 
error = function(err) {
  NA_character_
})}

list_markers=NULL
list_markers <- lapply(FUN=fun, "X"=list_iterable[[1]])

# add the gene and cluster as a column
list_markers <- mapply(function(df_markers, annots) {
  if (!all(sapply(df_markers, is.na))) {
    cbind("feature" = rownames(df_markers), "annotation"=rep(annots, nrow(df_markers)), df_markers)
  } else {
    NA_character_
  }
},
df_markers=list_markers, 
annot=names(table(Idents(SCOP))), SIMPLIFY=F)

# check for NAs from errors
list_markers <- list_markers[!sapply(list_markers, function(markers) all(is.na(markers)))]

# reduce list of dataframes to a single dataframe
df_markers_clust <- Reduce(x=list_markers, f=rbind)
rownames(df_markers_clust) <- NULL

df_markers_clust$p_val_adj <- p.adjust(p=df_markers_clust$p_val, method="fdr")
#openxlsx::write.xlsx(x = df_markers_clust, file=here::here("pilot_data/Output/clusters.xlsx"))
#saveRDS(SCOP, here::here("pilot_data/SCOP_SCTransform.rds"))
SCOP <- readRDS(here::here("pilot_data/SCOP-SCTransform.rds"))

df_markers_clust <- openxlsx::read.xlsx(here::here("pilot_data/Output/clusters.xlsx"))

df_markers_clust_fdr <- df_markers_clust %>% 
  dplyr::filter(p_val_adj<0.05) %>% 
  dplyr::group_by(annotation) 
length(df_markers_clust_fdr)
df_markers_clust_fdr %>% dplyr::top_n(n = 2, wt = avg_log2FC) %>% View()


####Create figures####
Idents(SCOP)<-"HTO_classification"
SCOP <- RenameIdents(SCOP, 
                     "322-KO"="HNKO",
                     "342-WT"="WT",
                     "318-WT"="WT",
                     "328-KO"="HNKO",
                     "338-WT"="WT",
                     "344-KO"="HNKO")
SCOP$genotype <- Idents(SCOP)
DimPlot(SCOP, split.by = "genotype")
cell_types <- c("HNKO 1", 
                "Hepatocytes 1", 
                "Periportal 1",
                "HNKO 2",
                "Hepatocytes 2",
                "Hepatocytes 3",
                "HNKO 3",
                "Periportal 2",
                "Endothelial",
                "Central 1",
                "Periportal 3",
                "Hepatocytes 4",
                "Stellate",
                "CD45+ 1",
                "Central HNKO 1",
                "Kupfer",
                "Central HNKO 2",
                "Cholangiocyte 1",
                "CD45+ 2",
                "Cholangiocyte 2",
                "CD45+ 3")

Idents(SCOP) <- "seurat_clusters"

names(cell_types)<-levels(SCOP)
SCOP <- RenameIdents(SCOP, cell_types)
SCOP$cell_types <- Idents(SCOP)
#factor order of levels
SCOP$cell_types<- factor(SCOP$cell_types, levels = c(
  "Hepatocytes 1",
  "Hepatocytes 2",
  "Hepatocytes 3",
  "Hepatocytes 4",
  "Central 1",
  "Periportal 1",
  "Periportal 2",
  "Periportal 3",
  "HNKO 1", 
  "HNKO 2",
  "HNKO 3",
  "Central HNKO 1",
  "Central HNKO 2",
  "Endothelial",
  "Cholangiocyte 1",
  "Cholangiocyte 2",
  "Stellate",
  "Kupfer",
  "CD45+ 1",
  "CD45+ 2",
  "CD45+ 3"))

plot_markers <- c("Acaa1b", "Slc1a2" , "Glul","Cyp2f2","Cyp17a1", "Stab2", "Ptprb", "Ctnnd2","Spp1", "Dcn", "Rbms3",  "Hdac9","Inpp4b", "Timd4", "Ptprc")
Idents(SCOP)<-"cell_types"
DotPlot(SCOP,  features = plot_markers)+
  theme(axis.text.x = element_text(size = 8))
DimPlot(SCOP, split.by = "genotype")
#saveRDS(SCOP, here::here("pilot_data/SCOP_labeled.rds"))
SCOP <- readRDS(here::here("pilot_data/SCOP_labeled.rds"))
annot_clust = "SCT_snn_res.1.2"


vec_color_clust = colorRampPalette(brewer.pal(n=11, name="RdYlBu"))(length(unique(SCOP@meta.data$cell_types)))

names(vec_color_clust) = unique(SCOP@meta.data$cell_types)

DimPlot(SCOP, 
        group.by= "cell_types",
        cols = vec_color_clust,repel = T,pt.size = 0.1, label.size = 5,
        label = TRUE) + NoLegend()
#same plot but split by genotype
DimPlot(SCOP, 
        group.by= "cell_types",
        split.by = "genotype",
        #cols = vec_color_clust,repel = T,pt.size = 0.1, label.size = 3,
        label = TRUE) + NoLegend()

####Subset hepatocytes####
hepatocytes <- c("0","1", "2", "3", "4", "5", "6", "7", "9", "11", "14", "16")
SCOP_hepatocytes <- RunPCA(SCOP_hepatocytes, 
               npcs=npcs, 
               seed.use=randomSeed, 
               verbose=F)
#runUMAP
SCOP_hepatocytes  <- RunUMAP(SCOP_hepatocytes, 
                dims = 1:npcs, 
                seed.use = randomSeed+1)
SCOP_hepatocytes  <- FindNeighbors(SCOP_hepatocytes,
                      reduction = "pca", 
                      dims = 1:npcs)

SCOP_hepatocytes  <- FindClusters(SCOP_hepatocytes ,
                     random.seed = randomSeed, 
                     resolution = 1.2,
                     verbose = FALSE)


DimPlot(SCOP_hepatocytes)
annot_hash = "hash.ID"

vec_color_hash=wesanderson::wes_palette("Royal1")
vec_color_hash = c(vec_color_hash, wesanderson::wes_palette("Zissou1")[c(1,3)])

names(vec_color_hash) = unique(SCOP_hepatocytes@meta.data[[annot_hash]])
DimPlot(SCOP_hepatocytes, 
        group.by="hash.ID",
        cols = vec_color_hash,
        repel = T,
        pt.size = 0.1, label.size = 5,
        label = TRUE) + NoLegend()

#saveRDS(SCOP_hepatocytes, file = here("pilot_data/subset_analysis_hepatocytes_SCT.rds"))
SCOP_hepatocytes <- readRDS(here::here("pilot_data/subset_analysis_hepatocytes_SCT.rds"))
hepatocytes_features <- FindAllMarkers(SCOP_hepatocytes, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)

Idents(SCOP_hepatocytes)<-"HTO_classification"
SCOP_hepatocytes <- RenameIdents(SCOP_hepatocytes, 
                     "322-KO"="HNKO",
                     "342-WT"="WT",
                     "318-WT"="WT",
                     "328-KO"="HNKO",
                     "338-WT"="WT",
                     "344-KO"="HNKO")
SCOP_hepatocytes$genotype <- Idents(SCOP_hepatocytes)
DimPlot(SCOP_hepatocytes)
genotype_markers <- FindMarkers(SCOP_hepatocytes, ident.1 = "WT", ident.2 = "HNKO")
top_genes <- head(rownames(genotype_markers), 21)
top_genes <- as.data.frame(top_genes) %>%  dplyr::filter(!top_genes == "ENSMUSG00000118017")
Idents(SCOP_hepatocytes) <- "HTO_classification"
DotPlot(SCOP_hepatocytes, features = top_genes)

RidgePlot(SCOP_hepatocytes, features = c("ND4", "COX1"))
RidgePlot(SCOP_hepatocytes, features = top_genes$top_genes, ncol = 4)

#GO analysis
universe <- rownames(SCOP_hepatocytes)
bg = bitr(universe, 
          fromType = "SYMBOL", 
          toType = "ENTREZID", 
          OrgDb = "org.Mm.eg.db",
          drop = T)

eg<- bitr(rownames(genotype_markers), 
          fromType = "SYMBOL", 
          toType = "ENTREZID", 
          OrgDb = "org.Mm.eg.db",
          drop = T)

goResults_genotype <- enrichGO(gene = eg$ENTREZID,
                      universe = bg$ENTREZID,
                      OrgDb = org.Mm.eg.db,
                      ont = "BP")
dotplot(goResults_genotype, showCategory = 15)

goResults_genotype <- setReadable(goResults_genotype, org.Mm.eg.db, "ENTREZID")
cnetplot(goResults_genotype)

#upregulated genes
eg_up <- genotype_markers %>% 
  dplyr::filter(avg_log2FC > 0)

eg_up<- bitr(rownames(eg_up), 
          fromType = "SYMBOL", 
          toType = "ENTREZID", 
          OrgDb = "org.Mm.eg.db",
          drop = T)

goResults_up <- enrichGO(gene = eg_up$ENTREZID,
                               universe = bg$ENTREZID,
                               OrgDb = org.Mm.eg.db,
                               ont = "BP")
Up_reg <- dotplot(goResults_up, showCategory = 15) + ggplot2::ggtitle("Downregulated in HNKO")

eg_down <- genotype_markers %>% 
  dplyr::filter(avg_log2FC < 0)
eg_down <- bitr(rownames(eg_down), 
             fromType = "SYMBOL", 
             toType = "ENTREZID", 
             OrgDb = "org.Mm.eg.db",
             drop = T)

goResults_down <- enrichGO(gene = eg_down$ENTREZID,
                               universe = bg$ENTREZID,
                               OrgDb = org.Mm.eg.db,
                               ont = "BP")
Down_reg <- dotplot(goResults_down, showCategory = 15)+ggplot2::ggtitle("Upregulated in HNKO")

Up_reg + Down_reg

#openxlsx::write.xlsx(goResults_genotype, here::here("pilot_data/GO_genotype_SCT.xlsx"))

SCOP_hepatocytes$HTO_classification <- factor(SCOP_hepatocytes$HTO_classification, 
                                              levels = c("322-KO", "344-KO", "328-KO", "318-WT", "338-WT", "342-WT"))
Idents(SCOP_hepatocytes)<-"HTO_classification"
DotPlot(SCOP_hepatocytes, features = c("COX1", "Pck1", "Alb", "Glul"))

#####test knockouts wo phenotype against damage#####
Idents(SCOP_hepatocytes) <- "HTO_classification"
Markers_322 <- FindMarkers(SCOP_hepatocytes, ident.1 = "322-KO", ident.2 = "328-KO")
Markers_344 <- FindMarkers(SCOP_hepatocytes, ident.1 = "344-KO", ident.2 = "328-KO")


eg_322<- bitr(rownames(Markers_322), 
          fromType = "SYMBOL", 
          toType = "ENTREZID", 
          OrgDb = "org.Mm.eg.db",
          drop = T)

goResults_322 <- enrichGO(gene = eg_322$ENTREZID,
                               universe = bg$ENTREZID,
                               OrgDb = org.Mm.eg.db,
                               ont = "BP")
eg_344<- bitr(rownames(Markers_344), 
              fromType = "SYMBOL", 
              toType = "ENTREZID", 
              OrgDb = "org.Mm.eg.db",
              drop = T)

goResults_344 <- enrichGO(gene = eg_344$ENTREZID,
                          universe = bg$ENTREZID,
                          OrgDb = org.Mm.eg.db,
                          ont = "BP")
dotplot(goResults_322)
dotplot(goResults_344)
#hepatocytes cluster based on sample more than function. Try to make an upset plot and see distinct genes in each cluster?

hepatocyte_sig <- hepatocytes_features %>% 
  dplyr::filter(p_val_adj<0.05)
#openxlsx::write.xlsx(hepatocyte_sig, here::here("pilot_data/hepatocyte_sig_SCT.xlsx"))
hepatocyte_sig <- openxlsx::read.xlsx(here::here("pilot_data/hepatocyte_sig_SCT.xlsx"))

hepatocyte_sig %>% group_by(cluster) %>%  dplyr::top_n(n = 5, wt = avg_log2FC) %>% View()


hepatocyte_list <- list(Cluster_0 = NA,
                        Cluster_1 = NA,
                        Cluster_2 = NA,
                        Cluster_3 = NA,
                        Cluster_4 = NA,
                        Cluster_5 = NA,
                        Cluster_6 = NA,
                        Cluster_7 = NA,
                        Cluster_8 = NA,
                        Cluster_9 = NA,
                        Cluster_10 = NA,
                        Cluster_11 = NA,
                        Cluster_12 = NA)
for (i in 0:12){
  genes <- hepatocyte_sig %>% 
    dplyr::filter(cluster == i)
  hepatocyte_list[[sum(i+1)]]<- genes$gene
}
UpSetR::upset(UpSetR::fromList(hepatocyte_list), order.by = "freq", nsets = 13)


#prepare dataanalysis for clusterprofiler GO
universe <- rownames(SCOP)
bg = bitr(universe, 
          fromType = "SYMBOL", 
          toType = "ENTREZID", 
          OrgDb = "org.Mm.eg.db",
          drop = T)

cluster_GO<- list(Cluster_0 = NA,
                  Cluster_1 = NA,
                  Cluster_2 = NA,
                  Cluster_3 = NA,
                  Cluster_4 = NA,
                  Cluster_5 = NA,
                  Cluster_6 = NA,
                  Cluster_7 = NA,
                  Cluster_8 = NA,
                  Cluster_9 = NA,
                  Cluster_10 = NA,
                  Cluster_11 = NA,
                  Cluster_12 = NA)

for (i in 0:12){
  candidates <- hepatocyte_list[[sum(i+1)]]
  eg<- bitr(candidates, 
            fromType = "SYMBOL", 
            toType = "ENTREZID", 
            OrgDb = "org.Mm.eg.db",
            drop = T)
  
  goResults <- enrichGO(gene = eg$ENTREZID,
                        universe = bg$ENTREZID,
                        OrgDb = org.Mm.eg.db,
                        ont = "BP")
  cluster_GO[sum(i+1)]<-goResults
  
}
#openxlsx::write.xlsx(cluster_GO, here::here("pilot_data/cluster_GO_SCT.xlsx"))
for (i in 1:13){
  cluster_GO[[i]]<- openxlsx::read.xlsx(here::here("pilot_data/cluster_GO_SCT.xlsx"),i)
}

#####annotate based on top non-pseudogene marker####

marker_genes <- c("Sds_1",
                  "Cyp3a41a",
                  "Ntrk2",
                  "Sord",
                  "Rtn4",
                  "Zbtb16",
                  "ND4",
                  "Sds_2",
                  "Slco1a1",
                  "Slc1a2_1",
                  "Slc1a2_2",
                  "Chrm3",
                  "Slc1a2_3")
Idents(SCOP_hepatocytes)<-"seurat_clusters"
names(marker_genes)<-levels(SCOP_hepatocytes)
SCOP_hepatocytes <- RenameIdents(SCOP_hepatocytes, marker_genes)
SCOP_hepatocytes$marker_genes<- Idents(SCOP_hepatocytes)
Idents(SCOP_hepatocytes)<-"marker_genes"
SCOP_hepatocytes$genotype <- factor(SCOP_hepatocytes$genotype, c("WT", "HNKO"))
DimPlot(SCOP_hepatocytes,split.by = "genotype", label = T, repel = T,pt.size = 0.1, label.size = 5)+ NoLegend()+ggplot2::ggtitle("Cluster Genes for Hepatocyte Subpopulations")+ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
#factor order of levels
SCOP$cell_types<- factor(SCOP$cell_types, levels = c() )


#####code from John#####
library(SCOPfunctions)
#df_DE_genes <- DE_MAST_RE_seurat(
  # object = SCOP_hepatocytes,
  # random_effect.vars = "HTO_classification",
  # ident.1 = "HNKO",
  # group.by = "genotype") 


