library(tidyverse)
library(here)
library(Seurat)
library(cowplot)
library(biomaRt)
library(org.Mm.eg.db)
library(clusterProfiler)

SCOP_2021_0132.210202_liver <-
  readRDS(here(
    "pilot_data/Output/data/SCOP_2021_0132.210202_liver.raw.rds"
  ))
VlnPlot(
  SCOP_2021_0132.210202_liver,
  features = c("nFeature_RNA", "nCount_RNA"),
  ncol = 2
)



plot1 <-
  FeatureScatter(SCOP_2021_0132.210202_liver,
                 feature1 = "nCount_RNA",
                 feature2 = "nFeature_RNA")

SCOP_2021_0132.210202_liver <-
  subset(SCOP_2021_0132.210202_liver, subset = nFeature_RNA > 200 &
           nFeature_RNA < 2500)

SCOP_2021_0132.210202_liver <-
  NormalizeData(
    SCOP_2021_0132.210202_liver,
    normalization.method = "LogNormalize",
    scale.factor =
  )

SCOP_2021_0132.210202_liver <-
  FindVariableFeatures(SCOP_2021_0132.210202_liver,
                       selection.method = "vst",
                       nfeatures = 2000)
top10 <- head(VariableFeatures(SCOP_2021_0132.210202_liver), 10)
plot1 <- VariableFeaturePlot(SCOP_2021_0132.210202_liver)
plot2 <- LabelPoints(plot = plot1,
                     points = top10,
                     repel = T)
plot1 + plot2

all.genes <- rownames(SCOP_2021_0132.210202_liver)
SCOP_2021_0132.210202_liver <-
  ScaleData(SCOP_2021_0132.210202_liver, features = all.genes)

SCOP_2021_0132.210202_liver <-
  RunPCA(SCOP_2021_0132.210202_liver,
         features = VariableFeatures(object = SCOP_2021_0132.210202_liver))
VizDimLoadings(SCOP_2021_0132.210202_liver,
               dims = 1:2,
               reduction = "pca")
DimPlot(SCOP_2021_0132.210202_liver, reduction = "pca")
DimHeatmap(
  SCOP_2021_0132.210202_liver,
  dims = 1:13,
  cells = 500,
  balanced = T
)

SCOP_2021_0132.210202_liver <-
  JackStraw(SCOP_2021_0132.210202_liver, num.replicate = 100)
SCOP_2021_0132.210202_liver <-
  ScoreJackStraw(SCOP_2021_0132.210202_liver, dims = 1:20)
JackStrawPlot(SCOP_2021_0132.210202_liver, dims = 1:15)
ElbowPlot(SCOP_2021_0132.210202_liver)

SCOP_2021_0132.210202_liver <- FindNeighbors(SCOP_2021_0132.210202_liver, dims = 1:10)
SCOP_2021_0132.210202_liver <- FindClusters(SCOP_2021_0132.210202_liver, resolution = 0.5)
head(Idents(SCOP_2021_0132.210202_liver),5)

SCOP_2021_0132.210202_liver <- RunUMAP(SCOP_2021_0132.210202_liver, dims = 1:10, verbose = F)
Idents(SCOP_2021_0132.210202_liver)<- "HTO_classifications"
DimPlot(SCOP_2021_0132.210202_liver)

DimPlot(SCOP_2021_0132.210202_liver, reduction = "umap")
#saveRDS(SCOP_2021_0132.210202_liver, file = here("pilot_data/data_analysis_seurat_tutorial/data_post_umap"))
DimPlot(SCOP_2021_0132.210202_liver, reduction = "hto.umap")

cluster1.markers <- FindMarkers(SCOP_2021_0132.210202_liver, ident.1 = 2, min.pct = 0.25)
SCOP.markers <- FindAllMarkers(SCOP_2021_0132.210202_liver, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)

SCOP.markers %>% group_by(cluster) %>%  top_n(n=2, wt = avg_log2FC) %>% View()
FeaturePlot(SCOP_2021_0132.210202_liver, features = c("Glul", "Hal", "Cyp3a41a", "Fmo3", "Stab2", "Slc8a1", "Ptprb", "Robo2", "Nrxn1", "Hdac9"))

#####Load in and analyze data generated by SCOP#####
SCOP<- readRDS(here("pilot_data/Output/data/SCOP_2021_0132.210202_liver.umap.rds"))
  #save plot with HTO labels
hto_plot <- DimPlot(SCOP)

#Cluster cells  
SCOP <- FindNeighbors(SCOP, dims = 1:10)
SCOP <- FindClusters(SCOP, resolution = 0.5)
head(Idents(SCOP),5)

DimPlot(SCOP, reduction = "umap")
dim_plot <- DimPlot(SCOP, reduction = "umap")
DimPlot(SCOP, split.by = "HTO_classification")

SCOP.markers <- FindAllMarkers(SCOP, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)
SCOP.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_log2FC)
#saveRDS(SCOP.markers, here('pilot_data/SCOP_markers.rds'))
VlnPlot(SCOP, features = "Sds")
p <- FeaturePlot(SCOP, features = "Cps1", split.by = "HTO_classification", combine = F)
plot_grid(plotlist = p, ncol = 4)

#saveRDS(SCOP, here('pilot_data/SCOP_after_clustering.rds'))
SCOP <-readRDS(here("pilot_data/SCOP_after_clustering.rds"))
DimPlot(SCOP)
p <- FeaturePlot(SCOP, features = "Glul", split.by = "HTO_classification", combine = F)
plot_grid(plotlist = p, ncol = 3)

##### try clusterprofiler to explore clusters####

universe <- rownames(SCOP)
bg = bitr(universe, 
          fromType = "SYMBOL", 
          toType = "ENTREZID", 
          OrgDb = "org.Mm.eg.db",
          drop = T)
cluster_markers <- list(cluster.0 = NA,
                        cluster.1 = NA,
                        cluster.2 = NA,
                        cluster.3 = NA,
                        cluster.4 = NA,
                        cluster.5 = NA,
                        cluster.6 = NA,
                        cluster.7 = NA,
                        cluster.8 = NA,
                        cluster.9 = NA,
                        cluster.10 = NA,
                        cluster.11 = NA)

for (i in 0:11){
  candidates <- SCOP.markers %>% 
    dplyr::filter(cluster == i & p_val_adj<0.05) %>% 
    dplyr::select(gene)
  
  eg<- bitr(candidates$gene, 
           fromType = "SYMBOL", 
           toType = "ENTREZID", 
           OrgDb = "org.Mm.eg.db",
           drop = T)
  
  goResults <- enrichGO(gene = eg$ENTREZID,
                        universe = bg$ENTREZID,
                        OrgDb = org.Mm.eg.db,
                        ont = "BP")
  cluster_markers[sum(i+1)]<-goResults
  
}

for (i in 1:12){
  cluster_markers[[i]]<- setReadable(cluster_markers[[i]], OrgDb = org.Mm.eg.db, keyType="ENTREZID")
}
#saveRDS(cluster_markers, here('pilot_data/GOresults.rds'))
View(cluster_markers[1])  
dotplot(cluster_markers[[1]])
FeaturePlot(SCOP, split.by = "HTO_classification", features = "Glul")
VlnPlot(SCOP, features = "Alb")
DimPlot(SCOP)
DimPlot(SCOP, split.by= "HTO_classification")
dotplot(GOresults[[1]])
DimPlot(SCOP, split.by = "seurat_clusters", combine = F)
