library(tidyverse)
library(here)
library(Seurat)
library(cowplot)
library(biomaRt)
library(org.Mm.eg.db)
library(clusterProfiler)


#####Load in and analyze data generated by SCOP#####
SCOP<- readRDS(here("pilot_data/Output/data/SCOP_2021_0132.210202_liver.umap.rds"))
  #save plot with HTO labels
hto_plot <- DimPlot(SCOP)

#Cluster cells  
SCOP <- FindNeighbors(SCOP, dims = 1:10)
SCOP <- FindClusters(SCOP, resolution = 0.5)
head(Idents(SCOP),5)

DimPlot(SCOP, reduction = "umap")
dim_plot <- DimPlot(SCOP, reduction = "umap")
DimPlot(SCOP, split.by = "HTO_classification")

SCOP.markers <- FindAllMarkers(SCOP, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)
SCOP.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_log2FC)
#saveRDS(SCOP.markers, here('pilot_data/SCOP_markers.rds'))
SCOP.markers<-readRDS(here('pilot_data/SCOP_markers.rds'))
VlnPlot(SCOP, features = "Sds")
p <- FeaturePlot(SCOP, features = "Cps1", split.by = "HTO_classification", combine = F)
plot_grid(plotlist = p, ncol = 4)
#saveRDS(SCOP, here('pilot_data/SCOP_after_clustering.rds'))

#####Data after analysis####
SCOP <-readRDS(here("pilot_data/SCOP_after_clustering.rds"))
DimPlot(SCOP)
p <- FeaturePlot(SCOP, features = "Glul", split.by = "HTO_classification", combine = F)
plot_grid(plotlist = p, ncol = 3)

##### try clusterprofiler to explore clusters####

universe <- rownames(SCOP)
bg = bitr(universe, 
          fromType = "SYMBOL", 
          toType = "ENTREZID", 
          OrgDb = "org.Mm.eg.db",
          drop = T)
cluster_markers <- list(cluster.0 = NA,
                        cluster.1 = NA,
                        cluster.2 = NA,
                        cluster.3 = NA,
                        cluster.4 = NA,
                        cluster.5 = NA,
                        cluster.6 = NA,
                        cluster.7 = NA,
                        cluster.8 = NA,
                        cluster.9 = NA,
                        cluster.10 = NA,
                        cluster.11 = NA)

for (i in 0:11){
  candidates <- SCOP.markers %>% 
    dplyr::filter(cluster == i & p_val_adj<0.05) %>% 
    dplyr::select(gene)
  
  eg<- bitr(candidates$gene, 
           fromType = "SYMBOL", 
           toType = "ENTREZID", 
           OrgDb = "org.Mm.eg.db",
           drop = T)
  
  goResults <- enrichGO(gene = eg$ENTREZID,
                        universe = bg$ENTREZID,
                        OrgDb = org.Mm.eg.db,
                        ont = "BP")
  cluster_markers[sum(i+1)]<-goResults
  
}

for (i in 1:12){
  cluster_markers[[i]]<- setReadable(cluster_markers[[i]], OrgDb = org.Mm.eg.db, keyType="ENTREZID")
}
#saveRDS(cluster_markers, here('pilot_data/GOresults.rds'))
GoResults <- readRDS(here('pilot_data/GOresults.rds'))

#####Explore plots####
FeaturePlot(SCOP, split.by = "HTO_classification", features = "Glul")
VlnPlot(SCOP, features = "Alb")
DimPlot(SCOP)
DimPlot(SCOP, split.by= "HTO_classification")
dotplot(GOresults[[1]])
DimPlot(SCOP, split.by = "seurat_clusters", combine = F)

#####explore clusters####
cluster.0<- SCOP.markers %>% 
  dplyr::filter(cluster ==0 & p_val_adj < 0.05)
View(cluster.0)

####Mapping test####
non_hepatocytes <- c("7", "8", "9", "10", "11")
SCOP_subset <- subset(SCOP, subset = seurat_clusters %in% non_hepatocytes)
DimPlot(SCOP_subset)  
SCOP_subset <- ScaleData(SCOP_subset)
#SCOP_subset <- FindVariableFeatures(SCOP_subset, verbose = F)
SCOP_subset <- RunPCA(SCOP_subset)
ElbowPlot(SCOP_subset, ndims = 50)
SCOP_subset <- RunUMAP(SCOP_subset, dims = 1:13, verbose = F)
DimPlot(SCOP_subset)

SCOP_subset <- FindNeighbors(SCOP_subset, dims = 1:13)
SCOP_subset <- FindClusters(SCOP_subset, resolution = 0.5)
DimPlot(SCOP_subset)
subset_features <- FindAllMarkers(SCOP_subset, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)
#saveRDS(SCOP_subset, file = here("pilot_data/subset_analysis.rds"))
#saveRDS(subset_features, file = here("pilot_data/subset_features.rds"))
DimPlot(SCOP_subset, split.by = "HTO_classification")
SCOP_subset <- readRDS(here("pilot_data/subset_analysis.rds"))
subset_features <- readRDS(here("pilot_data/subset_features.rds"))

####Subset hepatocytes####
hepatocytes <- c("0","1", "2", "3", "4", "5", "6")
SCOP_hepatocytes <- subset(SCOP, subset = seurat_clusters %in% hepatocytes)
SCOP_hepatocytes <- ScaleData(SCOP_hepatocytes)
#SCOP_hepatocytes <- FindVariableFeatures(SCOP_hepatocytes, verbose = F)
SCOP_hepatocytes <- RunPCA(SCOP_hepatocytes)
ElbowPlot(SCOP_hepatocytes, ndims = 50)
SCOP_hepatocytes <- RunUMAP(SCOP_hepatocytes, dims = 1:16, verbose = F)

SCOP_hepatocytes <- FindNeighbors(SCOP_hepatocytes, dims = 1:16)
SCOP_hepatocytes <- FindClusters(SCOP_hepatocytes, resolution = 0.5)
DimPlot(SCOP_hepatocytes)
#saveRDS(SCOP_hepatocytes, file = here("pilot_data/subset_analysis_hepatocytes.rds"))
hepatocytes_features <- FindAllMarkers(SCOP_hepatocytes, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)
#hepatocytes cluster based on sample more than function. Try to make an upset plot and see distinct genes in each cluster?
install.packages("UpSetR")
library(UpSetR)
hepatocyte_deg <- SCOP.markers %>% 
  dplyr::filter(cluster %in% hepatocytes) %>% 
  dplyr::filter(p_val_adj<0.05)
hepatocyte_list <- list(Cluster_0 = NA,
                        Cluster_1 = NA,
                        Cluster_2 = NA,
                        Cluster_3 = NA,
                        Cluster_4 = NA,
                        Cluster_5 = NA,
                        Cluster_6 = NA)
for (i in 0:6){
  genes <- hepatocyte_deg %>% 
    dplyr::filter(cluster == i)
  hepatocyte_list[[sum(i+1)]]<- genes$gene
}
upset(fromList(hepatocyte_list), order.by = "freq", nsets = 7)

#extract unique genes
universe <- rownames(SCOP)
bg = bitr(universe, 
          fromType = "SYMBOL", 
          toType = "ENTREZID", 
          OrgDb = "org.Mm.eg.db",
          drop = T)
cluster_uniques <- list(Cluster_0 = NA,
                             Cluster_1 = NA,
                             Cluster_2 = NA,
                             Cluster_3 = NA,
                             Cluster_4 = NA,
                             Cluster_5 = NA,
                             Cluster_6 = NA)
cluster_GO<- list(Cluster_0 = NA,
                  Cluster_1 = NA,
                  Cluster_2 = NA,
                  Cluster_3 = NA,
                  Cluster_4 = NA,
                  Cluster_5 = NA,
                  Cluster_6 = NA)

for (i in 0:6){
  candidates <- hepatocyte_deg %>% 
    dplyr::filter(cluster == i)
  ref <- hepatocyte_deg %>% 
    dplyr::filter(cluster != i)
  candidates <- candidates %>% 
    dplyr::filter(!(gene %in% ref$gene))
  cluster_uniques[[sum(i+1)]]<- candidates
  }

for (i in 0:6){
  candidates <- cluster_uniques[[sum(i+1)]]$gene
  eg<- bitr(candidates, 
            fromType = "SYMBOL", 
            toType = "ENTREZID", 
            OrgDb = "org.Mm.eg.db",
            drop = T)
  
  goResults <- enrichGO(gene = eg$ENTREZID,
                        universe = bg$ENTREZID,
                        OrgDb = org.Mm.eg.db,
                        ont = "BP")
  cluster_GO[sum(i+1)]<-goResults
  
}
#saveRDS(cluster_GO, file = here("pilot_data/GO_data_hepatocytes.rds"))
#saveRDS(cluster_uniques, file = here("pilot_data/hepatocyte_cluster_genes.rds"))
for (i in 1:6){
  cluster_GO[[i]]<- setReadable(cluster_GO[[i]], OrgDb = org.Mm.eg.db, keyType="ENTREZID")
}

dotplot(cluster_GO[[1]])
